# Generated by Django 5.1.6 on 2026-01-27 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rapport',
        ),
    ]
